### ISSUE TITLE
Unable to run the tests

### ISSUE THREAD

**Issue by hemraj-s** [morenoh149/react-native-contacts-test#5]
I am getting an error when running the tests on my machine. The error is as follows:
```
 FAIL  __tests__\index.android.js
  ? Test suite failed to run

    E:/react-native/react-native-contacts-test-master/__tests__/index.android.js
: Unexpected token (10:4)
         8 | it('renders correctly', () => {
         9 |   const tree = renderer.create(
      > 10 |     <Index />
           |     ^
        11 |   );
        12 | });
        13 |
```
Can you help please. 

Steps that I followed:
1. Extracted the folder 
2. Ran "yarn install"
3. Ran "npm test"

TIA

**Comment by morenoh149** [comment]
I bet it's a babel config issue.

**Comment by hemraj-s** [comment]
Can you help with more details to help fix the same.
TIA

**Comment by morenoh149** [comment]
I'm not sure, but I'd look into the babel config and making sure that the `Index` component is available. I can look into this when I have time but I have no eta.

**Comment by hemraj-s** [comment]
Thanks for the pointer. Will go through and check it out. Appreciate the help.
